title: "Agricola La&nbsp;Mezza&nbsp;Luna"
whatsapp_number: "+393345613301"
sheet_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRiJPgQT7WtIBEJ-1oSmDnVlRA85hsBIRz2RnJNcarIaN5awMmh-UJc_TwCeQ5lXOc_sA70RoPxLet0/pub?output=csv"
url: "https://lamezzaluna.eu"
baseurl: ""

# Informazioni Legali
company_name: "La&nbsp;Mezza&nbsp;Luna di Leoluca&nbsp;Clini"
address: "Via&nbsp;Lampara&nbsp;38, Punta&nbsp;Marina"
p_iva: "[XXXXXXXXXXX]"
codice_fiscale: "[XXXXXXXXXXXXXXX]"
rea: "[XX-XXXXXX]"
email: "[xxxxxxxxxx@xxxxxx]"