title: "Agricola La Mezza Luna"
whatsapp_number: "393345613301"
sheet_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQfuyKN0VDDVw9wil0C9gXieyh1MnZjyRbijRqf9tQzmuThtVErJjkqkR2GE1IRBGuCS1FH0iR0-hAK/pub?output=csv"
url: "https://digitalcreat0r.github.io" 
baseurl: "/sitoweb_leo"

# Informazioni Legali
company_name: "La Mezza Luna di Leoluca Clini"
address: "[scrivere la via]"
p_iva: "[XXXXXXXXXXXX]"
codice_fiscale: "[XXXXXXXXXXXXXXX]"
rea: "[XX-XXXXXX]"
email: "[xxxxxxxxxx@xxxxxx]"